
SQLHost: "127.0.0.1" # Host of your sql database.

SQLPort: "3306" # Port of database

# NOTE: Database will not create automatically
SQLDatabaseName: "Eco" # Database name

SQLUserName: "root" # Name of user in database

SQLPassword: "" # Username`s password.

SQLSSL: "false" # IF YOUR HOST PROTECTED WITH SSL CONNECTION MAKE IT "true"!

