
SQL:
  HOST: "localhost" # IP ADDRESS OF DATABASE PROVIDER
  PORT: "3306" # PORT OF DATABASE PROVIDER
  DATABASE: "eco" # DATABASE
  USER: "root" # USERNAME
  PASSWORD: "" # PASSWORD FOR USERNAME
  SSL: "false" # MAKE IT "true" WHEN PROVIDER PROTECTED DATABASE WITH SSL.